# Generated by Django 5.0.14 on 2026-06-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(default='Full-time', max_length=50)),
                ('experience_required', models.FloatField(default=0.0)),
                ('salary_range', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiters.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_have_skills', models.JSONField(blank=True, default=list)),
                ('nice_to_have_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('experience_required', models.FloatField(default=0.0)),
                ('seniority', models.CharField(blank=True, default='', max_length=50)),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='jobs.job')),
            ],
        ),
    ]
