# Generated by Django 5.0.14 on 2026-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
